### ISSUE TITLE
Migrate generation of L100_OpenStudio_Simulation schematron to new CSV method

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/TestSuite#24]

**Comment by nllong** [comment]
@macintoshpie or @corymosiman12 -- has this happened?

**Comment by corymosiman12** [comment]
Yes - the CSV is here:

https://github.com/BuildingSync/TestSuite/blob/develop/schematron/v2.2.0/v2-2-0_L100_OpenStudio_Pre-Simulation.csv
