### ISSUE TITLE
What are Capacity requirements for Condenser

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/TestSuite#30]
## Context
STD 211 6.2.1.3.a states `System design capacity (kW, Btu/h, and/or tons)` for HVAC Systems. Cooling Plants, Heating Plants and Deliveries have capacities, but `auc:CondenserPlant` does not.

BEDES does not have any reference for condenser plant capacities.

## Task
Determine ASHRAE's definition for condenser plant capacities. Resolution of this issue is to either
1. Decide it's not necessary, and we won't check for it
2. Decide it is necessary and insert it at the level of `auc:CondenserPlant/*/auc:Capacity` - this is the approach of other plant types (have capacity inside of the specific type, e.g. AirCooled, WaterCooled, GroundSource, GlycolCooledDryCooler). Or insert it at the level of `auc:CondenserPlant/auc:Capacity`.

**Comment by nllong** [comment]
Sorry for the delay. It appears that this is necessary. I would use the same approach as the other instances (`auc:CondenserPlant/*/auc:Capacity`).

**Comment by macintoshpie** [comment]
Addressed here: f8621eb171610d3a4d8d1cd39dd0ca68bf51ebfe
