### ISSUE TITLE
Do we need auc:Capacity for HeatingPlant types?

### ISSUE THREAD

**Issue by macintoshpie** [BuildingSync/TestSuite#31]
## Context
STD 211 6.2.1.3.a requires `System design capacity (kW, Btu/h, and/or tons)` for HVAC systems. In BuildingSync, CoolingPlants (e.g. auc:Chiller and auc:DistrictChilledWater) have child elements `auc:Capacity` (same for `auc:Delivery`, and `auc:CoolingSource`.

However, `auc:HeatingPlant` types (as well as `auc:HeatingSource`) have `auc:InputCapacity` and `auc:OutputCapacity`.

## Task
Why does `auc:HeatingPlant` and `auc:HeatingSource` have these different capacity elements? Should they also include `auc:Capacity`?

**Comment by macintoshpie** [comment]
Just to confirm, do we want to make this change for all of these cases?
- auc:HeatingPlant/auc:Boiler
- auc:HeatingPlant/auc:DistrictHeating
- auc:HeatingPlant/auc:SolarThermal
- auc:HeatingAndCoolingSystems/auc:HeatingSources/auc:HeatingSource

**Comment by nllong** [comment]
yes, change `OutputCapacity` to `Capacity` in all of those cases.

**Comment by macintoshpie** [comment]
Addressed here: 6d3a4d93335fd7e9b3c16afa7d52a2a56d79cdad
