### ISSUE TITLE
Determine Exempt Section Types

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/TestSuite#42]
Originally brought up in PR #37

> @corymosiman12 What should the auc:SectionType be for something like a Parking deck? We currently require any Space function to have linked lighting, hvac, etc, which I'm guessing we wouldn't want to for users to include.
> 
> This came up because I was trying to create a space that's excluded from the gross and conditioned floor area values (see above).
> ...
> Ah yeah, I think I should have a different OccupancyClassification. I guess I'm trying to figure out how we know which of the Space functions we should make the extra assertions on

**Comment by macintoshpie** [comment]
@corymosiman12 to determine requirements for every OccupancyClassification type:
- linked lighting 
- plugs/process loads
- hvac

**Comment by corymosiman12** [comment]
ok @macintoshpie added a new sheet 'SectionType Requirements' to the google doc

**Comment by corymosiman12** [comment]
@nllong want to review?  maybe went a lil too overkill...?

**Comment by nllong** [comment]
can you send the link to the google doc?

**Comment by corymosiman12** [comment]
done

**Comment by macintoshpie** [comment]
Great, implemented here: 95ae962
